### ISSUE TITLE
Correction to file extension - many eyes audit reviews

### ISSUE THREAD

**Issue by JennySimmons** [chrisbrowneanu/virtuousloop#1]
Hi Chris,

I don't know the process for doing this but I will try this method.
The link created to the audit review feedback in many eyes is incorrect.
Line 668 in analysis_many_eyes.py needs to be changed from:
 comment = "<a href=\"" + cfg['assignment']['feedback_url'] + **"reviews/"** + this_user + "-" + secret + ".pdf\">PDF Feedback on your Reviews</a>"
 to:
  comment = "<a href=\"" + cfg['assignment']['feedback_url'] + **"/reviews/**" + this_user + "-" + secret + ".pdf\">PDF Feedback on your Reviews</a>"

currently the link will create /PA1reviews/ and I would prefer it to be /PA1/reviews/

Thanks
Jenny

**Comment by chrisbrowneanu** [comment]
@JennySimmons - fixed - see how that goes :)
